Add new font

diff --git a/.chezmoiscripts/run_once_before_30-install-font.sh.tmpl b/.chezmoiscripts/run_once_before_30-install-font.sh.tmpl
--- a/.chezmoiscripts/run_once_before_30-install-font.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_30-install-font.sh.tmpl
@@ -1,19 +1,24 @@
-{{ if (and (eq .chezmoi.os "linux" ) (not .headless)) -}}
+{{ if (and (eq .chezmoi.os "linux") (not .headless) (ne .chezmoi.username "root")) -}}
 #!/bin/bash
 
 set -eufo pipefail
 
 # List of Nerd Fonts font to install
 nerdfonts_fonts=(UbuntuMono Hack)
+# List of urls to download font, supported files can be .ttf or .zip
+font_urls=(
+  https://ftp.gnu.org/gnu/unifont/unifont-14.0.01/unifont-14.0.01.ttf
+)
 font_dir=~/.local/share/fonts
 
 # renovate: depName=ryanoasis/nerd-fonts
 current_nerdfonts_version=v2.1.0
 
+echo -e "\033[0;32m>>>>> Begin Setting Up Font <<<<<\033[0m"
 updated_counter=0
 for font in ${nerdfonts_fonts[@]}; do
   if $(fc-list | grep -i "$font Nerd Font" &> /dev/null); then
-    echo "$font already installed"
+    echo "$font is already installed"
   else
     echo "installing $font"
     mkdir -p $font_dir/$font
@@ -22,8 +27,36 @@ for font in ${nerdfonts_fonts[@]}; do
   fi
 done
 
+for font in ${font_urls[@]}; do
+  font_file=$(basename $font)
+  font_name=$(echo $font_file | cut -d '.' -f1 | cut -d '-' -f1)
+  file_ext=${font_file##*.}
+  if $(fc-list | grep -i "$font_name" &> /dev/null); then
+    echo "$font_name is already installed"
+  else
+    echo "installing $font_name"
+    mkdir -p $font_dir/$font_name
+    case $file_ext in
+      zip)
+        curl -fLo $font_dir/$font_name.zip $font && unzip -o $font_dir/$font_name.zip -d $font_dir/$font_name && rm $font_dir/$font_name.zip
+        updated_counter=$((updated_counter + 1))
+        ;;
+      ttf|otf|pcf|xcf)
+        cd $font_dir/$font_name && curl -fLO $font
+        updated_counter=$((updated_counter + 1))
+        ;;
+      *)
+        echo -e "\033[0;31m[ERROR]unsupported file format $font_file\033[0m"
+        exit 1
+        ;;
+    esac
+  fi
+done
+
 # reset font cache
 if [ $updated_counter -gt 0 ]; then
+  echo "refreshing font cache"
   fc-cache -vf "$font_dir"
 fi
+echo -e "\033[0;32m>>>>> Finish Setting Up Font <<<<<\033[0m"
 {{ end -}}
